# Generated by Django 5.2.3 on 2025-07-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
