# Generated by Django 5.2.7 on 2025-10-05 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен начинаться с 79 и содержать 11 цифр, например: 79529999999', regex='^79\\d{9}$')], verbose_name='Phone number'),
        ),
    ]
