# Generated by Django 5.2.7 on 2025-11-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_address_order_city_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.paymentmethod', verbose_name='Метод'),
        ),
    ]
