# Generated by Django 5.2.7 on 2025-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активен'),
        ),
    ]
